<?php
use Migrations\AbstractSeed;

/**
 * US Seed
 *
 * Seeds the tables with top 100 US names
 *
 * @category Seed
 * @package  ClearSky.NameGen
 * @author   Mike Tallroth <mike.tallroth@goclearsky.com>
 * @license  http://www.opensource.org/licenses/mit-license.php The MIT License
 * @link     http://github.com/goclearsky/cakephp-name-gen
 */
class NameGenUsSeed extends AbstractSeed
{

    // source: https://www.rong-chang.com/namesdict/100_last_names.htm
    public $familyNames = [
        [ 'id' => null, 'name' => 'Adams', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Alexander', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Allen', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Anderson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Bailey', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Baker', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Barnes', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Bell', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Bennett', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Brooks', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Brown', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Bryant', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Butler', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Campbell', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Carter', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Clark', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Coleman', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Collins', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Cook', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Cooper', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Cox', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Davis', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Diaz', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Edwards', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Evans', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Flores', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Foster', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Garcia', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gonzales', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gonzalez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gray', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Green', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Griffin', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Hall', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Harris', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Hayes', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Henderson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Hernandez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Hill', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Howard', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Hughes', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jackson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'James', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jenkins', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Johnson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jones', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kelly', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'King', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Lee', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Lewis', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Long', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Lopez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Martin', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Martinez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Miller', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Mitchell', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Moore', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Morgan', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Morris', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Murphy', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Nelson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Parker', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Patterson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Perez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Perry', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Peterson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Phillips', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Powell', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Price', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ramirez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Reed', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Richardson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Rivera', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Roberts', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Robinson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Rodriguez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Rogers', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ross', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Russell', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Sanchez', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Sanders', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Scott', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Simmons', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Smith', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Stewart', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Taylor', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Thomas', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Thompson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Torres', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Turner', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Walker', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ward', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Washington', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Watson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'White', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Williams', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Wilson', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Wood', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Wright', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Young', 'locale' => 'en_US' ],
    ];

    // source: https://www.ssa.gov/oact/babynames/decades/century.html
    public $givenNames = [

        // female names
        [ 'id' => null, 'name' => 'Abigail', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Alexis', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Alice', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Amanda', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Amber', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Amy', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Andrea', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Angela', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ann', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Anna', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ashley', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Barbara', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Betty', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Beverly', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Brenda', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Brittany', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Carol', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Carolyn', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Catherine', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Cheryl', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Christina', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Christine', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Cynthia', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Danielle', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Deborah', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Debra', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Denise', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Diana', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Diane', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Donna', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Doris', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Dorothy', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Elizabeth', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Emily', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Emma', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Evelyn', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Frances', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gloria', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Grace', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Hannah', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Heather', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Helen', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jacqueline', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jane', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Janet', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Janice', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jean', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jennifer', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jessica', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Joan', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Joyce', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Judith', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Judy', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Julia', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Julie', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Karen', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Katherine', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kathleen', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kathryn', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kayla', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kelly', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kimberly', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Laura', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Lauren', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Linda', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Lisa', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Lori', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Madison', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Margaret', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Maria', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Marie', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Marilyn', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Martha', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Mary', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Megan', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Melissa', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Michelle', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Nancy', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Natalie', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Nicole', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Olivia', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Pamela', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Patricia', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Rachel', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Rebecca', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Rose', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ruth', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Samantha', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Sandra', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Sara', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Sarah', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Sharon', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Shirley', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Stephanie', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Susan', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Teresa', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Theresa', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Tiffany', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Victoria', 'gender' => 'F', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Virginia', 'gender' => 'F', 'locale' => 'en_US' ],

        // male names
        [ 'id' => null, 'name' => 'Aaron', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Adam', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Alan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Albert', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Alexander', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Andrew', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Anthony', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Arthur', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Austin', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Benjamin', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Billy', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Bobby', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Brandon', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Brian', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Bruce', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Bryan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Carl', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Charles', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Christian', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Christopher', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Daniel', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'David', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Dennis', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Donald', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Douglas', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Dylan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Edward', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Eric', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ethan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Eugene', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Frank', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gabriel', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gary', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'George', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gerald', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Gregory', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Harold', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Harry', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Henry', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jack', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jacob', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'James', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jason', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jeffrey', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jeremy', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jerry', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jesse', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Joe', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'John', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Johnny', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jonathan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jordan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Jose', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Joseph', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Joshua', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Juan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Justin', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Keith', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kenneth', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kevin', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Kyle', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Larry', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Lawrence', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Logan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Louis', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Mark', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Matthew', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Michael', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Nathan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Nicholas', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Noah', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Patrick', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Paul', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Peter', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Philip', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ralph', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Randy', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Raymond', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Richard', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Robert', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Roger', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ronald', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Roy', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Russell', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Ryan', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Samuel', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Scott', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Sean', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Stephen', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Steven', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Terry', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Thomas', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Timothy', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Tyler', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Vincent', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Walter', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Wayne', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'William', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Willie', 'gender' => 'M', 'locale' => 'en_US' ],
        [ 'id' => null, 'name' => 'Zachary', 'gender' => 'M', 'locale' => 'en_US' ],
    ];

    public function run()
    {
        $Table = $this->table('name_gen_family');
        $Table->insert($this->familyNames)->save();
        $Table = null;

        $Table = $this->table('name_gen_given');
        $Table->insert($this->givenNames)->save();
        $Table = null;

        $Table = $this->table('name_gen_middle');
        $Table->insert($this->givenNames)->save();
        $Table = null;
    }

}
